apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-ports
  namespace: {{ .Values.namespace }}
data:
  BACKEND_PORT: "{{ .Values.backend.service.port }}"
  FRONTEND_PORT: "{{ .Values.frontend.service.port }}"
  POSTGRES_PORT: "{{ .Values.postgres.service.port }}"
